export const lightTheme = {
  background: "#fff",
  text: "#000",
  primary: "#7b2cbf",
  secondary: "#9688B2",
  text2: "#7b2cbf",
  searchBarBackground: "#f0f0f0",
  searchBarPlaceHolderText: "#aaa",
  postBodyText: "#555",
  bottomBorder: "gray",
  iconsGrey: "grey",
  commentBackground: "#DADADA",
  cardBackground: "#fff",
  shadow: "#1A1A1A",
  dateGrey: "#aaa",
  reportRed: "#d32f2f",
};

export const darkTheme = {
  background: "#1A1A1A",
  text: "#fff",
  primary: "#7b2cbf",
  secondary: "#9688B2",
  text2: "#9688B2",
  searchBarBackground: "#333",
  searchBarPlaceHolderText: "#888",
  postBodyText: "#ccc",
  bottomBorder: "#444",
  iconsGrey: "#fff",
  commentBackground: "#2A2A2A",
  cardBackground: "#2A2A2A",
  shadow: null,
  dateGrey: "#aaa",
  reportRed: "#ff6b6b",
};
